# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "18wa9ffxgq7llcz8hnv2kfbc2ppxqc29y7203fgrwx0ngkq919w0";
    aarch64-linux = "0v9sqfjf8lgc3ymdvzpnxnfvf160h85y77m6ifx23bpdkaz4zmhn";
    x86_64-darwin = "0i6f3xldpdxdh5928rjcm4c5s7ba7qia7gdn924bagq6w7jhmyaa";
    aarch64-darwin = "1xhff5kxirsra5xx8sfc27qi6l3c9y2c9g71zkml4whk1zm4c16g";
  };

  urlMap = {
    x86_64-linux = "https://github.com/arnodel/jsonstream/releases/download/v0.1.8/jsonstream_0.1.8_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/arnodel/jsonstream/releases/download/v0.1.8/jsonstream_0.1.8_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/arnodel/jsonstream/releases/download/v0.1.8/jsonstream_0.1.8_macOS_amd64.tar.gz";
    aarch64-darwin = "https://github.com/arnodel/jsonstream/releases/download/v0.1.8/jsonstream_0.1.8_macOS_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "jp";
  version = "0.1.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jp $out/bin/jp
  '';

  system = system;

  meta = {
    description = "JSON stream processor and transformation tool";
    homepage = "https://github.com/arnodel/jsonstream";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
